export const seedItems=[
{id:"eat-77valley",category:"eat",list:"restaurants",title:"77 Valley",mealType:"dinner",status:"done",tryAgain:true,effort:"normal",timeHorizon:"soon",priority:"normal",budget:"mid",duration:"1-2h",location:"77 Valley",addedBy:"Charlie",updatedBy:"Charlie",doneAt:null,ratings:{Charlie:null,Tayla:null},reviews:{Charlie:"",Tayla:""},tags:["pizza","acai"],cover:null,gallery:[],comments:[],reactions:{}},
{id:"eat-steaks",category:"eat",list:"cook-together",title:"Home cooking: steaks",mealType:"dinner",status:"done",tryAgain:false,effort:"normal",timeHorizon:"soon",priority:"normal",budget:"mid",duration:"1-2h",location:"Home",addedBy:"Charlie",updatedBy:"Charlie",doneAt:null,ratings:{Charlie:null,Tayla:null},reviews:{Charlie:"",Tayla:""},tags:["home","cook together"],cover:null,gallery:[],comments:[],reactions:{}},
{id:"eat-pasta",category:"eat",list:"cook-together",title:"Home cooking: pasta",mealType:"dinner",status:"done",tryAgain:false,effort:"normal",timeHorizon:"soon",priority:"normal",budget:"cheap",duration:"1-2h",location:"Home",addedBy:"Charlie",updatedBy:"Charlie",doneAt:null,ratings:{Charlie:null,Tayla:null},reviews:{Charlie:"",Tayla:""},tags:["home","cook together"],cover:null,gallery:[],comments:[],reactions:{}},
{id:"do-bowling",category:"do",list:"rematches",title:"Bowling — Brass Monkey",status:"done",tryAgain:true,effort:"normal",timeHorizon:"soon",priority:"high",doSoon:true,budget:"mid",duration:"1-2h",location:"Brass Monkey",addedBy:"Charlie",updatedBy:"Charlie",doneAt:null,ratings:{Charlie:null,Tayla:null},reviews:{Charlie:"",Tayla:""},tags:["rematch","challenge"],challenge:{stakes:"Rematch needed",winner:null,score:null},cover:null,gallery:[],comments:[],reactions:{}},
{id:"do-pool",category:"do",list:"date-ideas",title:"Pool day — W Palm",status:"done",tryAgain:false,effort:"normal",timeHorizon:"soon",priority:"normal",budget:"spenny",duration:"half-day",location:"W Palm",addedBy:"Charlie",updatedBy:"Charlie",doneAt:null,ratings:{Charlie:null,Tayla:null},reviews:{Charlie:"",Tayla:""},tags:["pool","daytime"],cover:null,gallery:[],comments:[],reactions:{}},
{id:"watch-hailmary",category:"watch",list:"films",title:"Project Hail Mary",status:"done",tryAgain:false,effort:"low",timeHorizon:"soon",priority:"normal",budget:"cheap",duration:"1-2h",location:"Home",addedBy:"Charlie",updatedBy:"Charlie",doneAt:null,ratings:{Charlie:null,Tayla:null},reviews:{Charlie:"",Tayla:""},tags:["film"],cover:null,gallery:[],comments:[],reactions:{}}
];
export const categoryMeta={
eat:{label:"Eat",emoji:"🍝",tone:"warm",sublists:[["restaurants","Restaurants","🍽️"],["coffee","Coffee","☕"],["dessert","Dessert","🍰"],["cook-together","Cook Together","🍳"],["drinks","Drinks","🍸"]]},
watch:{label:"Watch",emoji:"🎬",tone:"cinema",sublists:[["films","Films","🎞️"],["series","Series","📺"],["rewatch","Rewatch","🔁"]]},
go:{label:"Go",emoji:"✈️",tone:"airy",sublists:[["holidays","Holidays","🌍"],["staycations","Staycations","🏨"],["day-trips","Day Trips","🚗"],["revisit","Revisit","↩️"]]},
do:{label:"Do",emoji:"🎳",tone:"playful",sublists:[["date-ideas","Date Ideas","🌙"],["weekend","Weekend Ideas","☀️"],["challenges","Challenges","🏆"],["rematches","Rematches","🎳"],["bucket","Bucket List","✨"]]}
};
export const quickShortcuts=["Tonight","Pick for us","Quick add","Try Again","Planned","Surprises","Recent activity"];

export const mealTypes=[["breakfast-brunch","Breakfast / Brunch"],["lunch","Lunch"],["dinner","Dinner"],["coffee-snack","Coffee / Snack"],["drinks","Drinks"],["any","Any"]];
