"use client";import{useState}from"react";
const Q=[["name","First things first. Who are we assessing?","text","Candidate identification"],["why","Why should we appoint you Passenger Princess?","textarea","Personal statement"],["snacks","You have 100 AED and 4 minutes at a petrol station. What's the snack haul?","textarea","Procurement assessment · There are wrong answers."],["aux","How would you describe your AUX credentials?","select",["Elite — no skips","Strong, with occasional questionable choices","Probationary — supervision advised","One-song-on-repeat risk"]],["navigation","The driver ignores your directions and misses the turn. Your response?","select",["Silent judgment","Immediate “I told you so”","Laugh and let it go","Referenced for 3–5 business years"]],["maintenance","Please disclose your maintenance requirements.","range","Self-assessment"],["duties","Which core responsibilities are you prepared to undertake?","textarea","Examples: DJ, snacks, navigation, moral support, looking exceptional."],["destination","Propose a location for the practical road test.","text","First-date planning assessment"],["final","Any final information for the hiring manager?","textarea","References, qualifications and tasteful bribery attempts accepted."]];
export default function Home(){
 const[start,setStart]=useState(false),[i,setI]=useState(0),[a,setA]=useState({maintenance:5}),[stage,setStage]=useState("form"),[contact,setContact]=useState({phone:"",instagram:""}),[busy,setBusy]=useState(false);
 const q=Q[i],v=a[q[0]]??"",set=v=>setA({...a,[q[0]]:v});
 async function next(){if(!String(v).trim()&&q[2]!=="range")return alert("Candidate response required before progression.");if(i<Q.length-1)return setI(i+1);setStage("contact")}
 async function submit(){if(!contact.phone.trim()&&!contact.instagram.trim())return alert("Talent Acquisition needs at least one approved communication channel.");setBusy(true);const payload={...a,...contact};const r=await fetch("/api/apply",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});setBusy(false);r.ok?setStage("complete"):alert("HR has suffered a technical incident. Try again.")}
 if(stage==="contact")return <main><div className="shell"><Header/><section className="success"><div className="seal">✓</div><div className="kicker">APPLICATION COMPLETE · FINAL ADMINISTRATION</div><h1>How should we contact you?</h1><p>Your application has passed the paperwork stage. Should you progress, Talent Acquisition requires at least one approved communication channel.</p><div className="review"><label className="kicker">MOBILE NUMBER</label><input placeholder="+971…" value={contact.phone} onChange={e=>setContact({...contact,phone:e.target.value})}/><label className="kicker">INSTAGRAM</label><input placeholder="@username" value={contact.instagram} onChange={e=>setContact({...contact,instagram:e.target.value})}/></div><button onClick={submit}>{busy?"LODGING CANDIDATE FILE…":"COMPLETE CANDIDATE FILE →"}</button><p className="legal">Provide one or both. Instagram is accepted for entirely professional candidate due diligence.</p></section></div></main>;
 if(stage==="complete")return <main><div className="shell"><Header/><section className="success"><div className="seal">✓</div><div className="kicker">CANDIDATE FILE COMPLETE</div><h1>You're officially under consideration.</h1><p>Your application is now with the hiring manager. Please await further correspondence.</p><div className="review"><Row a="CURRENT STATUS" b="SCREENING"/><Row a="NEXT STAGE" b="IN-PERSON ROAD TEST"/><Row a="HIRING MANAGER" b="CHARLIE"/></div><p className="legal">Excessive lobbying may or may not improve your chances.</p></section></div></main>;
 if(!start)return <main><div className="shell"><Header/><section className="hero"><div className="vacancy"><span>VACANCY PP-001</span><span className="live">● APPLICATIONS OPEN</span></div><div className="kicker">TALENT ACQUISITION · DUBAI</div><h1>Passenger<br/>Princess</h1><p className="intro">We are seeking one exceptional candidate to occupy a highly competitive position within the Passenger Operations division.</p><div className="spec"><Row a="LOCATION" b="PASSENGER SEAT"/><Row a="DEPARTMENT" b="LOGISTICS & VIBES"/><Row a="EMPLOYMENT TYPE" b="SUBJECT TO CHEMISTRY"/><Row a="VACANCIES" b="1"/></div><h3>COMPENSATION & BENEFITS</h3><div className="chips"><span>Climate control</span><span>AUX access*</span><span>Door-to-door transport*</span><span>Snack opportunities</span><span>Occasional compliments</span></div><button onClick={()=>setStart(true)}>START APPLICATION <b>→</b></button><p className="legal">*Privileges subject to performance, chemistry and hiring-manager discretion. Passenger Princess™ is an equal-opportunity fictional employer.</p></section></div></main>;
 let field=q[2]==="textarea"?<textarea placeholder="Type your response…" value={v} onChange={e=>set(e.target.value)}/>:q[2]==="select"?<div className="options">{q[3].map(x=><button key={x} className={v===x?"selected":""} onClick={()=>set(x)}><i>{v===x?"●":"○"}</i>{x}</button>)}</div>:q[2]==="range"?<div className="range"><div className="score">{v}<small>/10</small></div><input type="range" min="1" max="10" value={v} onChange={e=>set(e.target.value)}/><div className="ends"><span>Low maintenance</span><span>Dedicated support required</span></div></div>:<input placeholder="Type your response…" value={v} onChange={e=>set(e.target.value)}/>;
 return <main><div className="shell"><Header/><div className="stages"><span className="active">APPLICATION</span><span className={i>3?"active":""}>COMPATIBILITY</span><span className={i>6?"active":""}>ROAD TEST</span><span>REVIEW</span></div><section className="form"><div className="qmeta"><span>{q[3] instanceof Array?"CANDIDATE ASSESSMENT":q[3]}</span><span>{String(i+1).padStart(2,"0")} / {String(Q.length).padStart(2,"0")}</span></div><h2>{q[1]}</h2>{field}<div className="nav">{i>0&&<button className="secondary" onClick={()=>setI(i-1)}>← BACK</button>}<button onClick={next}>{i===Q.length-1?"LODGE APPLICATION →":"CONTINUE →"}</button></div></section></div></main>
}
function Header(){return <header><div className="brand"><span className="mark">PP</span><div><b>PASSENGER PRINCESS™</b><small>TALENT ACQUISITION</small></div></div><span className="secure">PRIVATE & CONFIDENTIAL</span></header>}function Row({a,b}){return <div className="row"><span>{a}</span><b>{b}</b></div>}