"use client";import{useEffect,useState}from"react";import{useParams}from"next/navigation";import{pillowQuestions}from"../../../lib/pillowQuestions";
export default function Pillow(){const{token}=useParams();const[data,setData]=useState(null),[mode,setMode]=useState("loading"),[i,setI]=useState(0),[answers,setAnswers]=useState({}),[reveal,setReveal]=useState(0),[shown,setShown]=useState(false),[busy,setBusy]=useState(false);const q=pillowQuestions[i];
useEffect(()=>{if(!token)return;fetch("/api/pillow/"+token).then(r=>r.json()).then(d=>{setData(d);if(d.answers)setAnswers(d.answers);if(d.status==="RELEASED")setMode("ready");else if(d.status==="AWAITING_RESPONSE")setMode("waiting");else setMode("intro")})},[token]);
const section=q?.section||"BEFORE";const klass=section.toLowerCase();function set(v){setAnswers({...answers,[q.id]:v})}function valid(){const v=answers[q.id];if(q.type==="matrix")return v&&q.items.every(x=>v[x]);if(q.type==="multi")return Array.isArray(v)&&v.length>0;return v!==undefined&&String(v).trim()!==""}
async function next(){if(!valid())return alert("No skipping the interesting bits.");if(i<pillowQuestions.length-1)setI(i+1);else await submit()}
async function submit(){setBusy(true);const r=await fetch("/api/pillow/"+token,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({answers})});setBusy(false);if(r.ok){setMode("waiting");setData({...data,status:"AWAITING_RESPONSE",answers})}else alert("Something went wrong saving the file.")}
function toggleMulti(x){const a=answers[q.id]||[];set(a.includes(x)?a.filter(v=>v!==x):[...a,x])}
async function checkStatus(){const r=await fetch("/api/pillow/"+token,{cache:"no-store"});const d=await r.json();setData(d);if(d.status==="RELEASED")setMode("ready")}
if(mode==="loading")return <main className="pillow-bg"><div className="pillow-shell"><section className="pillow-center">Opening private file…</section></div></main>;
if(mode==="intro")return <main className="pillow-bg"><div className="pillow-shell before"><PHeader data={data}/><section className="pillow-hero"><div className="pillow-kicker">PRIVATE COMPATIBILITY FILE</div><h1>Pillow<br/>Princess</h1><p className="pillow-lead">The Passenger Princess paperwork was only phase one. This one is less about where we're going and slightly more about what happens when we get there.</p><div className="pillow-meta"><span>BEFORE</span><span>DURING</span><span>AFTER</span></div><button className="pillow-primary" onClick={()=>setMode("form")}>UNLOCK THE FILE →</button><p className="pillow-fine">Private link. Preferences can be updated. Clear boundaries remain undefeated.</p></section></div></main>;
if(mode==="waiting")return <main className="pillow-bg"><div className="pillow-shell after"><PHeader data={data}/><section className="pillow-center"><div className="pillow-seal">✓</div><div className="pillow-kicker">COMPATIBILITY FILE SUBMITTED</div><h2>Your answers are being considered.</h2><p>Some responses may require further thought. Or follow-up questions. Or a practical demonstration of excellent communication.</p><div className="pillow-status"><span>STATUS</span><b>AWAITING COUNTER-RESPONSE</b></div><div className="waiting-actions"><button className="pillow-primary" onClick={checkStatus}>CHECK FOR RESPONSE →</button><button className="pillow-secondary" onClick={()=>{setI(0);setMode("form")}}>EDIT MY ANSWERS</button></div><p className="pillow-fine">Come back to this same private link once you've been told the response is ready. If this page is already open, tap “Check for response”.</p></section></div></main>;
if(mode==="ready")return <main className="pillow-bg"><div className="pillow-shell during"><PHeader data={data}/><section className="pillow-center">{reveal===0&&!shown?<><div className="pillow-kicker">COUNTER-RESPONSE READY</div><h2>Your compatibility review is waiting.</h2><p>Nothing is revealed until you tap. Dramatic tension is apparently now a feature.</p><button className="pillow-primary" onClick={()=>setShown(true)}>TAP TO BEGIN →</button></>:<Reveal data={data} index={reveal} shown={shown} setShown={setShown} next={()=>{if(reveal<pillowQuestions.length-1){setReveal(reveal+1);setShown(false)}else setMode("done")}}/>}</section></div></main>;
if(mode==="done")return <main className="pillow-bg"><div className="pillow-shell after"><PHeader data={data}/><section className="pillow-center"><div className="pillow-seal">♥</div><div className="pillow-kicker">REVIEW COMPLETE</div><h2>Further research appears justified.</h2><p>Preferences noted. Boundaries respected. Several points may require discussion in a less administrative setting.</p><button className="pillow-secondary" onClick={()=>{setReveal(0);setShown(false);setMode("ready")}}>REPLAY THE REVEAL</button></section></div></main>;
let field=null;
if(q.type==="choice")field=<div className="pillow-options">{q.options.map(x=><button className={answers[q.id]===x?"selected":""} onClick={()=>set(x)} key={x}>{x}</button>)}</div>;
if(q.type==="multi")field=<div className="pillow-options multi">{q.options.map(x=><button className={(answers[q.id]||[]).includes(x)?"selected":""} onClick={()=>toggleMulti(x)} key={x}>{x}</button>)}</div>;
if(q.type==="range")field=<div className="pillow-range"><div className="pillow-score">{answers[q.id]||5}<small>/10</small></div><input type="range" min={q.min} max={q.max} value={answers[q.id]||5} onChange={e=>set(e.target.value)}/><div><span>{q.left}</span><span>{q.right}</span></div></div>;
if(q.type==="text")field=<textarea className="pillow-text" value={answers[q.id]||""} placeholder={q.placeholder} onChange={e=>set(e.target.value)}/>;
if(q.type==="matrix")field=<div className="pillow-matrix">{q.items.map(item=><div className="matrix-row" key={item}><b>{item}</b><div>{q.options.map(o=><button key={o} className={answers[q.id]?.[item]===o?"selected":""} onClick={()=>set({...answers[q.id],[item]:o})}>{o}</button>)}</div></div>)}</div>;
return <main className="pillow-bg"><div className={"pillow-shell "+klass}><PHeader data={data}/><div className="pillow-progress"><span style={{width:((i+1)/pillowQuestions.length*100)+"%"}}/></div><section className="pillow-form"><div className="pillow-qmeta"><span>{section}</span><span>{String(i+1).padStart(2,"0")} / {pillowQuestions.length}</span></div><h2>{q.label}</h2>{field}<div className="pillow-nav">{i>0&&<button className="pillow-secondary" onClick={()=>setI(i-1)}>← BACK</button>}<button className="pillow-primary" onClick={next}>{i===pillowQuestions.length-1?(busy?"SUBMITTING…":"SUBMIT FILE →"):"CONTINUE →"}</button></div></section></div></main>}
function PHeader({data}){return <header className="pillow-header"><div className="brand"><span className="mark pillow-mark">PP</span><div><b>PILLOW PRINCESS</b><small>PRIVATE COMPATIBILITY</small></div></div><span className="secure">{data?.candidateId?"PP-"+data.candidateId:"PRIVATE"}</span></header>}
function Reveal({data,index,shown,setShown,next}){const q=pillowQuestions[index],a=data.answers?.[q.id],r=data.responses?.[q.id];return <div className="reveal-card"><div className="pillow-qmeta"><span>{q.section}</span><span>{index+1} / {pillowQuestions.length}</span></div><h2>{q.label}</h2><RevealValue label="YOUR ANSWER" q={q} value={a}/>{!shown?<button className="pillow-primary" onClick={()=>setShown(true)}>TAP TO REVEAL RESPONSE</button>:<><RevealValue label="COUNTER-RESPONSE" q={q} value={r} counter/><button className="pillow-primary" onClick={next}>{index===pillowQuestions.length-1?"FINISH REVIEW →":"NEXT →"}</button></>}</div>}
function RevealValue({label,q,value,counter}){if(q.type==="matrix")return <div className={counter?"counter":"reveal-answer"}><small>{label}</small><div className="reveal-matrix">{q.items.map(item=><div key={item}><span>{item}</span><b>{value?.[item]||"—"}</b></div>)}</div></div>;return <div className={counter?"counter":"reveal-answer"}><small>{label}</small><p>{format(value)}</p></div>}
function format(v){if(Array.isArray(v))return v.join(" · ");if(v&&typeof v==="object")return Object.entries(v).map(([k,x])=>k+": "+x).join(" · ");return String(v??"—")}
