"use client";import{useEffect,useState}from"react";import{useParams}from"next/navigation";
const choices=[
["Bowling rematch + something sweet","Current record: 0–2. A rematch has been formally requested."],
["Coffee + a wander","Low admin. Good coffee. More time together."],
["Chill night","Pizza, film, acai, and negotiations regarding a certain oversized black T-shirt."],
["Dealer's choice","You pick the vibe. I handle the plan."],
["Custom request","For candidates with their own agenda."]
];
export default function Programme(){const{token}=useParams();const[data,setData]=useState(null),[screen,setScreen]=useState("loading"),[noCount,setNoCount]=useState(0),[choice,setChoice]=useState([]),[custom,setCustom]=useState(""),[preferredTime,setPreferredTime]=useState(""),[note,setNote]=useState(""),[busy,setBusy]=useState(false);
useEffect(()=>{fetch("/api/programme/"+token).then(r=>r.json()).then(d=>{setData(d);setScreen(d.selection?"done":"status");if(d.selection){setChoice(Array.isArray(d.selection.choice)?d.selection.choice:(d.selection.choice?[d.selection.choice]:[]));setCustom(d.selection.custom);setPreferredTime(d.selection.preferredTime);setNote(d.selection.note)}})},[token]);
function naughty(){setNoCount(n=>n+1)}\nfunction toggleChoice(v){setChoice(c=>c.includes(v)?c.filter(x=>x!==v):[...c,v])}
async function submit(){if(!choice.length)return alert("Pick at least one. Administrative standards still apply.");if(choice.includes("Custom request")&&!custom.trim())return alert("Custom means you actually have to suggest something.");setBusy(true);const r=await fetch("/api/programme/"+token,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({choice,custom,preferredTime,note})});setBusy(false);if(r.ok)setScreen("done");else alert("Programme admin has had a wobble. Try again.")}
if(screen==="loading")return <main className="programme-bg"><div className="programme-shell"><section className="programme-center">Loading programme file…</section></div></main>;
if(screen==="status")return <main className="programme-bg"><div className="programme-shell"><Header data={data}/><section className="programme-hero"><div className="programme-kicker">THE PRINCESS PROGRAMME · CONTINUATION REVIEW</div><h1>PP-001<br/>Tayla</h1><p className="programme-lead">You passed the paperwork. Twice. The practical stage has also been going suspiciously well.</p><div className="programme-status"><Row a="PASSENGER PRINCESS" b="PASSED ✓"/><Row a="PILLOW PRINCESS" b="PASSED ✓"/><Row a="PRACTICAL ASSESSMENT" b="GOING SUSPICIOUSLY WELL"/><Row a="PROGRAMME RENEWAL" b="PENDING"/></div><div className="programme-memory"><p><b>77 Valley:</b> pizza + acai.</p><small>acai isn't shit</small><p><b>Bowling:</b> Tayla 0 — Charlie 2.</p><p className="quote">“Watch me hit this strike.”<br/><span>— immediately hits strike</span></p><p><b>Rematch:</b> pending.</p><p><b>Vodka + apple juice:</b> rogue choice. Still nice.</p><p><b>Stop the Wedding:</b> apparently on permanent rotation.</p><p><b>Oversized black T-shirt:</b> still missing. Probably being worn right now.</p></div><button className="programme-primary" onClick={()=>setScreen("ask")}>CONTINUE REVIEW →</button></section></div></main>;
if(screen==="ask")return <main className="programme-bg"><div className="programme-shell"><Header data={data}/><section className="programme-center ask"><div className="programme-kicker">RENEWAL REQUEST</div><h2>I need another excuse to see you.</h2><p>Strictly for programme-continuity purposes, obviously.</p><div className="yesno"><button className="yes" onClick={()=>{setScreen("good");setTimeout(()=>setScreen("choices"),850)}}>YES</button><button onClick={naughty} className={"no no-"+Math.min(noCount,4)}>{noCount===0?"NO":noCount===1?"Tayla, behave.":noCount===2?"Bit rude.":noCount===3?"Try again.":"This option is no longer available."}</button></div></section></div></main>;
if(screen==="good")return <main className="programme-bg"><div className="programme-shell"><section className="good-girl">Good girl..</section></div></main>;
if(screen==="choices")return <main className="programme-bg"><div className="programme-shell"><Header data={data}/><section className="programme-form"><div className="programme-kicker">CHOOSE YOUR NEXT ASSESSMENT</div><h2>What are we doing?</h2><p className="programme-lead">Pick as many as you want. Apparently one date idea was not ambitious enough.</p><div className="date-options">{choices.map(([a,b])=><button key={a} className={choice.includes(a)?"chosen":""} onClick={()=>toggleChoice(a)}><b>{a}</b><span>{b}</span></button>)}</div>{choice.includes("Custom request")&&<textarea placeholder="Your idea…" value={custom} onChange={e=>setCustom(e.target.value)}/>}<input placeholder="Preferred day / time (optional)" value={preferredTime} onChange={e=>setPreferredTime(e.target.value)}/><textarea placeholder="Any additional dramatic requirements? (optional)" value={note} onChange={e=>setNote(e.target.value)}/><button className="programme-primary" disabled={busy} onClick={submit}>{busy?"SUBMITTING…":"LOCK IT IN →"}</button></section></div></main>;
return <main className="programme-bg"><div className="programme-shell"><Header data={data}/><section className="programme-center"><div className="programme-seal">♥</div><div className="programme-kicker">PROGRAMME RENEWAL APPROVED</div><h2>Excellent choice.</h2><div className="programme-status"><Row a="SELECTION" b={choice.map(x=>x==="Custom request"?custom:x).join(" · ")}/>{preferredTime&&<Row a="PREFERRED TIME" b={preferredTime}/>}<Row a="STATUS" b="APPROVED ✓"/></div><p className="sweet">I've liked these last 10 days more than I probably planned to.<br/>So yes, I'd like another excuse to see you.</p><a className="whatsapp" href={"https://wa.me/447596386263?text="+encodeURIComponent("Fine. The Princess Programme can continue. I picked: "+choice.map(x=>x==="Custom request"?custom:x).join(", ")+(preferredTime?" — "+preferredTime:"")+" x")}>SEND YOUR DECISION ON WHATSAPP →</a><p className="programme-fine">T-shirt return remains optional but monitored.</p></section></div></main>}
function Header(){return <header className="programme-header"><div className="brand"><span className="mark programme-mark">PP</span><div><b>THE PRINCESS PROGRAMME</b><small>CONTINUATION DIVISION</small></div></div><span className="secure">PP-001 · PRIVATE</span></header>}
function Row({a,b}){return <div className="programme-row"><span>{a}</span><b>{b}</b></div>}