import {kv} from "@vercel/kv";import crypto from "crypto";import {seedItems} from "../../../lib/usData";
const NS="us:";const parse=x=>!x?null:(typeof x==="string"?JSON.parse(x):x);const now=()=>new Date().toISOString();const itemsKey=NS+"items";const activityKey=NS+"activity";const listsKey=NS+"customLists";
async function ensureSeed(){const seeded=await kv.get(NS+"seeded");if(seeded)return;for(const item of seedItems)await kv.hset(itemsKey,{[item.id]:JSON.stringify({...item,createdAt:now(),updatedAt:now()})});await kv.set(NS+"seeded","1")}
function sessionId(req){return req.cookies.get("us_session")?.value||null}
async function sessionUser(req){const sid=sessionId(req);if(!sid)return null;const s=parse(await kv.get(NS+"session:"+sid));if(!s||s.expiresAt<Date.now())return null;return s.user}
export async function GET(req){await ensureSeed();const user=await sessionUser(req);if(!user)return Response.json({error:"Unauthorized"},{status:401});const raw=await kv.hgetall(itemsKey)||{};const items=Object.values(raw).map(parse);const activity=(await kv.lrange(activityKey,0,39)||[]).map(parse);const listRaw=await kv.hgetall(listsKey)||{};const customLists=Object.values(listRaw).map(parse);return Response.json({user,items,activity,customLists})}
export async function POST(req){await ensureSeed();const user=await sessionUser(req);if(!user)return Response.json({error:"Unauthorized"},{status:401});const body=await req.json();if(body.action==="createList"){const id="custom-"+crypto.randomUUID();const list={id,category:body.category||"do",name:(body.name||"New list").trim(),emoji:body.emoji||"✨",createdBy:user,createdAt:now(),updatedBy:user,updatedAt:now()};await kv.hset(listsKey,{[id]:JSON.stringify(list)});await kv.lpush(activityKey,JSON.stringify({id:crypto.randomUUID(),type:"created list",title:list.name,user,at:now()}));return Response.json({ok:true,list})}const id=crypto.randomUUID();const item={id,title:body.title||"Untitled",category:body.category||"do",list:body.list||"date-ideas",status:body.status||"idea",effort:body.effort||"normal",timeHorizon:body.timeHorizon||"soon",mealType:body.category==="eat"?(body.mealType||"any"):undefined,priority:body.priority||"normal",budget:body.budget||"",duration:body.duration||"",location:body.location||"",tags:body.tags||[],isSurprise:!!body.isSurprise,tryAgain:false,addedBy:user,updatedBy:user,createdAt:now(),updatedAt:now(),ratings:{Charlie:null,Tayla:null},reviews:{Charlie:"",Tayla:""},comments:[],reactions:{},gallery:[],cover:null,emoji:body.emoji||null};await kv.hset(itemsKey,{[id]:JSON.stringify(item)});await kv.lpush(activityKey,JSON.stringify({id:crypto.randomUUID(),type:"added",itemId:id,title:item.title,user,at:now()}));return Response.json({ok:true,item})}
export async function PATCH(req){await ensureSeed();const user=await sessionUser(req);if(!user)return Response.json({error:"Unauthorized"},{status:401});const body=await req.json();if(body.action==="updateList"){const currentList=parse(await kv.hget(listsKey,body.id));if(!currentList)return Response.json({error:"Not found"},{status:404});const list={...currentList,name:(body.name||currentList.name).trim(),emoji:body.emoji||"✨",updatedBy:user,updatedAt:now()};await kv.hset(listsKey,{[list.id]:JSON.stringify(list)});await kv.lpush(activityKey,JSON.stringify({id:crypto.randomUUID(),type:"updated list",title:list.name,user,at:now()}));return Response.json({ok:true,list})}const current=parse(await kv.hget(itemsKey,body.id));if(!current)return Response.json({error:"Not found"},{status:404});const item={...current,...body,updatedBy:user,updatedAt:now()};await kv.hset(itemsKey,{[item.id]:JSON.stringify(item)});await kv.lpush(activityKey,JSON.stringify({id:crypto.randomUUID(),type:"updated",itemId:item.id,title:item.title,user,at:now(),status:item.status}));return Response.json({ok:true,item})}
export async function DELETE(req){const user=await sessionUser(req);if(!user)return Response.json({error:"Unauthorized"},{status:401});const {id}=await req.json();await kv.hdel(itemsKey,id);await kv.lpush(activityKey,JSON.stringify({id:crypto.randomUUID(),type:"deleted",itemId:id,user,at:now()}));return Response.json({ok:true})}
